STYLE: Prefer using `https` instead of `http` in copyright notice
Prefer using `https` instead of `http` in copyright notice license link.

Changed in https://github.com/InsightSoftwareConsortium/ITK/pull/3428

Fixes:
```
/home/runner/work/ITKNDReg/ITKNDReg/include/itkMetamorphosisImageRegistrationMethodv4.h:9:
 error: Header mismatch:
 ://www.apache.org/licenses/LICENSE-2.0.txt (s://www.apache.org/licenses/LICENSE-2.0.txt) :
 Utilities/KWStyle/ITKHeader.h
/home/runner/work/ITKNDReg/ITKNDReg/include/itkMetamorphosisImageRegistrationMethodv4.hxx:9:
 error: Header mismatch:
 ://www.apache.org/licenses/LICENSE-2.0.txt (s://www.apache.org/licenses/LICENSE-2.0.txt) :
 Utilities/KWStyle/ITKHeader.h
/home/runner/work/ITKNDReg/ITKNDReg/include/itkTimeVaryingVelocityFieldSemiLagrangianIntegrationImageFilter.h:9:
 error: Header mismatch:
 ://www.apache.org/licenses/LICENSE-2.0.txt (s://www.apache.org/licenses/LICENSE-2.0.txt) :
 Utilities/KWStyle/ITKHeader.h
/home/runner/work/ITKNDReg/ITKNDReg/include/itkTimeVaryingVelocityFieldSemiLagrangianIntegrationImageFilter.hxx:9:
 error: Header mismatch:
 ://www.apache.org/licenses/LICENSE-2.0.txt (s://www.apache.org/licenses/LICENSE-2.0.txt) :
 Utilities/KWStyle/ITKHeader.h
/home/runner/work/ITKNDReg/ITKNDReg/include/itkTimeVaryingVelocityFieldSemiLagrangianTransform.h:9:
 error: Header mismatch:
 ://www.apache.org/licenses/LICENSE-2.0.txt (s://www.apache.org/licenses/LICENSE-2.0.txt) :
 Utilities/KWStyle/ITKHeader.h
/home/runner/work/ITKNDReg/ITKNDReg/include/itkTimeVaryingVelocityFieldSemiLagrangianTransform.hxx:9:
 error: Header mismatch:
 ://www.apache.org/licenses/LICENSE-2.0.txt (s://www.apache.org/licenses/LICENSE-2.0.txt) :
 Utilities/KWStyle/ITKHeader.h
/home/runner/work/ITKNDReg/ITKNDReg/include/itkWrapExtrapolateImageFunction.h:9:
 error: Header mismatch:
 ://www.apache.org/licenses/LICENSE-2.0.txt (s://www.apache.org/licenses/LICENSE-2.0.txt) :
 Utilities/KWStyle/ITKHeader.h
/home/runner/work/ITKNDReg/ITKNDReg/test/itkMetamorphosisImageRegistrationMethodv4Test.cxx:9:
 error: Header mismatch:
 ://www.apache.org/licenses/LICENSE-2.0.txt (s://www.apache.org/licenses/LICENSE-2.0.txt) :
 Utilities/KWStyle/ITKHeader.h
/home/runner/work/ITKNDReg/ITKNDReg/test/itkTimeVaryingVelocityFieldSemiLagrangianIntegrationImageFilterTest.cxx:9:
 error: Header mismatch:
 ://www.apache.org/licenses/LICENSE-2.0.txt (s://www.apache.org/licenses/LICENSE-2.0.txt) :
 Utilities/KWStyle/ITKHeader.h
/home/runner/work/ITKNDReg/ITKNDReg/test/itkTimeVaryingVelocityFieldSemiLagrangianTransformTest.cxx:9:
 error: Header mismatch:
 ://www.apache.org/licenses/LICENSE-2.0.txt (s://www.apache.org/licenses/LICENSE-2.0.txt) :
 Utilities/KWStyle/ITKHeader.h
/home/runner/work/ITKNDReg/ITKNDReg/test/itkWrapExtrapolateImageFunctionTest.cxx:9:
 error: Header mismatch:
 ://www.apache.org/licenses/LICENSE-2.0.txt (s://www.apache.org/licenses/LICENSE-2.0.txt) :
 Utilities/KWStyle/ITKHeader.h
```

raised for example in:
https://github.com/InsightSoftwareConsortium/ITKNDReg/actions/runs/13094587832/job/36535317220?pr=27#step:14:60